import type { ProviderCredit, ProviderDiagnostic, ProviderReleaseCandidate, ProviderTrackMetadata, Release } from '../core/models.js';
import { normalizeArtist, normalizeDuration, normalizeTrackNumber, normalizeTitle } from '../core/normalization.js';
import { scoreRelease } from '../core/matching.js';
import { HttpClient } from '../shared/http.js';

export const DISCOGS_CAPABILITIES = { releaseSearch: true, isrc: false, credits: true, platformCheck: true } as const;
export function parseDiscogsUrl(url: string): { id: string; type: 'release' | 'master'; url: string } | undefined { const m = String(url).match(/discogs\.com\/(release|master)\/(\d+)/i); return m ? { id: m[2], type: m[1].toLowerCase() as 'release' | 'master', url: `https://www.discogs.com/${m[1].toLowerCase()}/${m[2]}` } : undefined; }
function apiUrl(id: string) { return `https://api.discogs.com/releases/${id}`; }
function durationMs(value: unknown) { const m = String(value ?? '').match(/^(\d+):([0-5]\d)$/); return m ? (Number(m[1]) * 60 + Number(m[2])) * 1000 : undefined; }
function roleName(role: string): string { return role.replace(/\s*\[[^\]]+\]/g, '').replace(/\s+/g, ' ').trim().toLowerCase(); }
function trackNumber(position: string): number | undefined { return normalizeTrackNumber(position); }
export function parseDiscogsRelease(json: any, sourceUrl?: string): { tracks: ProviderTrackMetadata[]; credits: ProviderCredit[]; candidate: ProviderReleaseCandidate } {
  const url = sourceUrl || json.uri || `https://www.discogs.com/release/${json.id}`; const tracklist = Array.isArray(json.tracklist) ? json.tracklist : []; const tracks: ProviderTrackMetadata[] = []; const credits: ProviderCredit[] = [];
  const title = String(json.title || ''); const artist = Array.isArray(json.artists) ? json.artists.map((a: any) => a.name).join(', ') : '';
  let medium = 1; for (const item of tracklist) { if (item.type_ === 'heading') { medium++; continue; } const children = item.type_ === 'index' && Array.isArray(item.sub_tracks) ? item.sub_tracks : [item]; for (const t of children) { const num = trackNumber(String(t.position || '')); const trackUrl = t.resource_url || url; tracks.push({ provider: 'discogs', sourceUrl: trackUrl, title: t.title || '', artist: Array.isArray(t.artists) ? t.artists.map((a: any) => a.name).join(', ') : artist, trackNumber: num, medium, durationMs: durationMs(t.duration), isrcs: [] }); for (const credit of [...(t.extraartists || []), ...(t.type_ === 'index' ? item.extraartists || [] : [])]) if (credit.name && credit.role) credits.push({ provider: 'discogs', sourceUrl: trackUrl, trackNumber: num, medium, role: roleName(credit.role), name: String(credit.name).replace(/\s*\(\d+\)\s*$/, '').trim(), attributes: [] }); } }
  for (const credit of json.extraartists || []) if (credit.name && credit.role) credits.push({ provider: 'discogs', sourceUrl: url, role: roleName(credit.role), name: String(credit.name).replace(/\s*\(\d+\)\s*$/, '').trim(), attributes: [] });
  const candidate: ProviderReleaseCandidate = { provider: 'discogs', id: String(json.id), url, title, artist, trackCount: tracks.length, barcode: json.barcode?.[0], year: json.year ? String(json.year) : undefined };
  return { tracks, credits, candidate };
}
export async function resolveDiscogs(release: Release, http: HttpClient): Promise<{ result?: ReturnType<typeof parseDiscogsRelease>; diagnostics: ProviderDiagnostic[] }> {
  const diagnostics: ProviderDiagnostic[] = []; const linked = release.links.find(l => l.provider === 'discogs' && parseDiscogsUrl(l.url)); let id = linked ? parseDiscogsUrl(linked.url)!.id : undefined; let linkedType = linked ? parseDiscogsUrl(linked.url)!.type : 'release';
  try {
    if (!id) { const query = release.barcode ? `barcode=${encodeURIComponent(release.barcode)}` : `q=${encodeURIComponent(`${release.artistCredit.map(a => a.name).join(' ')} ${release.title}`)}&type=release`; const data: any = await http.getJson(`https://api.discogs.com/database/search?${query}&per_page=10`, { cacheKey: `discogs-search-${normalizeTitle(release.title)}` }); const candidates: ProviderReleaseCandidate[] = (data.results || []).map((x: any) => ({ provider: 'discogs', id: String(x.id), url: `https://www.discogs.com/release/${x.id}`, title: x.title?.split(' - ').pop() || x.title || '', artist: x.title?.split(' - ')[0], trackCount: undefined, barcode: x.barcode?.[0] })); const ranked = candidates.map((c: ProviderReleaseCandidate) => ({ c, ...scoreRelease(release, c) })).sort((a: { score: number }, b: { score: number }) => b.score - a.score); if (ranked[0] && ranked[0].score >= .5) id = ranked[0].c.id; else { diagnostics.push({ provider: 'discogs', status: 'NO_MATCH', message: 'No candidate met title/artist matching threshold' }); return { diagnostics }; } }
    if (!id) return { diagnostics: [{ provider: 'discogs', status: 'NO_MATCH', message: 'Discogs release could not be resolved.' }] }; if (linkedType === 'master') { const master: any = await http.getJson(`https://api.discogs.com/masters/${id}`, { cacheKey: `discogs-master-${id}` }); if (!master.main_release) return { diagnostics: [{ provider: 'discogs', status: 'NO_MATCH', message: 'Discogs master has no main release.' }] }; id = String(master.main_release); }
    const response: any = await http.getJson(apiUrl(id), { cacheKey: `discogs-release-${id}` }); const result = parseDiscogsRelease(response, `https://www.discogs.com/release/${id}`); diagnostics.push({ provider: 'discogs', status: 'OK', url: result.candidate.url }); return { result, diagnostics };
  } catch (error) { diagnostics.push({ provider: 'discogs', status: 'NETWORK_ERROR', message: error instanceof Error ? error.message : String(error) }); return { diagnostics }; }
}
