import type { PlatformLink, ProviderCredit, ProviderDiagnostic, ProviderMatch, ProviderReleaseCandidate, ProviderTrackMetadata, Release, Track } from '../core/models.js';
import { compareTrack, scoreRelease } from '../core/matching.js';
import { normalizeArtist, normalizeIsrc, normalizeText } from '../core/normalization.js';
import { HttpClient } from '../shared/http.js';
import { resolveDiscogs } from './discogs.js';
import { parseQobuzAlbumUrl, qobuzIsrcs, resolveQobuz } from './qobuz.js';
import { parseTidalAlbumUrl, resolveTidal, tidalIsrcs } from './tidal.js';
import { resolveDeezer } from './deezer.js';

export const PROVIDERS = ['discogs', 'qobuz', 'tidal', 'deezer'] as const;
export const PROVIDER_CAPABILITIES = { discogs: { releaseSearch: true, isrc: false, credits: true, platformCheck: true }, qobuz: { releaseSearch: true, isrc: true, credits: true, platformCheck: true }, tidal: { releaseSearch: true, isrc: true, credits: true, platformCheck: true }, deezer: { releaseSearch: true, isrc: true, credits: false, platformCheck: true } } as const;
export interface IsrcRow { track: string; medium: number; existing: string[]; status: 'EXISTING' | 'MISSING' | 'MATCH' | 'CONFLICT'; candidates: ProviderMatch[]; diagnostics: ProviderDiagnostic[]; agreement: number; }
export interface CreditRow { track: string; medium?: number; role: string; person: string; provider: string; sourceUrl: string; existingMusicBrainzRelationship: boolean; candidate: string; confidence: number; evidence: string[]; }
export interface PlatformResult { platforms: PlatformLink[]; diagnostics: ProviderDiagnostic[]; }
interface ProviderResult { candidate?: ProviderReleaseCandidate; tracks: ProviderTrackMetadata[]; credits: ProviderCredit[]; diagnostics: ProviderDiagnostic[]; }
function existingLinks(release: Release, provider?: string) { return release.links.filter(l => !provider || l.provider === provider); }
function roleKey(value: string) { return normalizeText(value).replace(/\b(engineer|person|artist)\b/g, '').trim(); }
function externalResult(resolved: any): ProviderResult { return { candidate: resolved.result?.candidate, tracks: resolved.result?.tracks || [], credits: resolved.result?.credits || [], diagnostics: resolved.diagnostics || [] }; }
async function resolveProvider(release: Release, http: HttpClient, provider: string, needsIsrc = false): Promise<ProviderResult> { if (provider === 'discogs') return externalResult(await resolveDiscogs(release, http)); if (provider === 'qobuz') return externalResult(await resolveQobuz(release, http)); if (provider === 'tidal') return externalResult(await resolveTidal(release, http)); if (provider === 'deezer') return externalResult(await resolveDeezer(release, http, needsIsrc)); return { tracks: [], credits: [], diagnostics: [{ provider, status: 'UNSUPPORTED', message: 'No adapter registered.' }] }; }
function matchProviderTrack(track: Track, rows: ProviderTrackMetadata[], medium?: number): ProviderMatch | undefined { return rows.map(row => { const candidate: ProviderMatch = { provider: row.provider, url: row.sourceUrl, title: row.title, artist: row.artist, trackNumber: row.trackNumber, durationMs: row.durationMs, confidence: 0, decision: 'REJECT' }; const matched = compareTrack(track, candidate); if (medium != null && row.medium != null && row.medium === medium) matched.confidence = Math.min(1, matched.confidence + .05); return matched; }).sort((a, b) => b.confidence - a.confidence)[0]; }
function trackForCredit(release: Release, credit: ProviderCredit): Track | undefined { const tracks = release.mediums.flatMap(m => m.tracks); if (credit.trackNumber != null) { const exact = tracks.filter(t => t.number === credit.trackNumber && (credit.medium == null || t.medium === credit.medium)); if (exact.length) return exact[0]; } return undefined; }
function creditExists(track: Track | undefined, credit: ProviderCredit, release: Release): boolean { const rels = track ? track.relationships : release.relationships; return rels.some(r => r.targetName && normalizeArtist(r.targetName) === normalizeArtist(credit.name) && roleKey(r.type) === roleKey(credit.role)); }
export function classifyIsrcEvidence(existing: string[], candidates: Array<{ isrc?: string }>): { status: IsrcRow['status']; agreement: number; values: string[] } { const values = [...new Set(candidates.map(c => normalizeIsrc(c.isrc)).filter(Boolean))]; const normalizedExisting = existing.map(normalizeIsrc).filter(Boolean); const agreement = values.length ? Math.max(...values.map(v => candidates.filter(c => normalizeIsrc(c.isrc) === v).length)) : 0; const status = values.length > 1 ? 'CONFLICT' : normalizedExisting.length ? (values.length && !values.every(v => normalizedExisting.includes(v)) ? 'CONFLICT' : 'EXISTING') : values.length ? 'MATCH' : 'MISSING'; return { status, agreement, values }; }
export async function inspectCredits(release: Release, http: HttpClient, selected?: string, missingOnly = false): Promise<{ rows: CreditRow[]; diagnostics: ProviderDiagnostic[] }> { const providers = selected ? [selected] : [...PROVIDERS]; const results = await Promise.all(providers.map(p => resolveProvider(release, http, p))); const rows: CreditRow[] = []; const diagnostics = results.flatMap(r => r.diagnostics); for (const result of results) for (const credit of result.credits) { const track = trackForCredit(release, credit); const existing = creditExists(track, credit, release); const confidence = credit.trackNumber != null ? .9 : .65; const row: CreditRow = { track: track?.title || '[release]', medium: track?.medium, role: credit.role, person: credit.name, provider: credit.provider, sourceUrl: credit.sourceUrl, existingMusicBrainzRelationship: existing, candidate: credit.name, confidence, evidence: [credit.trackNumber != null ? 'provider track position' : 'provider release credit', existing ? 'matching MusicBrainz relationship' : 'no matching MusicBrainz relationship'] }; if (!missingOnly || !existing) rows.push(row); } return { rows, diagnostics }; }
async function providerIsrcTracks(release: Release, http: HttpClient, provider: string): Promise<{ tracks: ProviderTrackMetadata[]; diagnostics: ProviderDiagnostic[] }> { if (provider === 'qobuz') { const link = existingLinks(release, provider)[0]; const id = link && parseQobuzAlbumUrl(link.url)?.id; if (!id) return { tracks: [], diagnostics: [{ provider, status: 'NO_MATCH', message: 'No Qobuz album URL to resolve ISRCs.' }] }; const result = await qobuzIsrcs(id, http); return { tracks: result.tracks, diagnostics: [result.diagnostic] }; } if (provider === 'tidal') { const link = existingLinks(release, provider)[0]; const id = link && parseTidalAlbumUrl(link.url)?.id; if (!id) return { tracks: [], diagnostics: [{ provider, status: 'NO_MATCH', message: 'No Tidal album URL to resolve ISRCs.' }] }; const result = await tidalIsrcs(id, http); return { tracks: result.tracks, diagnostics: [result.diagnostic] }; } const result = await resolveProvider(release, http, provider, true); return { tracks: result.tracks, diagnostics: result.diagnostics }; }
export async function inspectIsrc(release: Release, http: HttpClient, selected?: string): Promise<IsrcRow[]> { const providers = selected ? [selected] : [...PROVIDERS]; const external = await Promise.all(providers.map(p => providerIsrcTracks(release, http, p))); return release.mediums.flatMap(m => m.tracks.map(track => ({ track, medium: m.position }))).map(({ track, medium }) => { const candidates: ProviderMatch[] = []; const diagnostics: ProviderDiagnostic[] = []; for (let i = 0; i < external.length; i++) { diagnostics.push(...external[i].diagnostics); const providerRows = external[i].tracks.filter(t => t.provider === providers[i]); const match = matchProviderTrack(track, providerRows, medium); if (!match || match.confidence < .4) continue; for (const row of providerRows.filter(t => t.isrcs.length && (t.trackNumber === track.number || match.url === t.sourceUrl))) for (const isrc of row.isrcs) candidates.push({ ...match, isrc: normalizeIsrc(isrc), evidence: [`${providers[i]} track match`, `title=${match.title || ''}`, `position=${match.trackNumber ?? '?'}`] }); } const existing = track.isrcs.map(normalizeIsrc).filter(Boolean); const summary = classifyIsrcEvidence(existing, candidates); return { track: track.title, medium, existing, status: summary.status, candidates, diagnostics, agreement: summary.agreement }; }); }
export async function inspectPlatforms(release: Release, http: HttpClient): Promise<PlatformResult> { const results = await Promise.all(PROVIDERS.map(p => resolveProvider(release, http, p))); const links: PlatformLink[] = []; const diagnostics = results.flatMap(r => r.diagnostics); for (let i = 0; i < results.length; i++) { const provider = PROVIDERS[i]; const existing = existingLinks(release, provider)[0]; const result = results[i]; if (existing) { const expected = release.mediums.flatMap(m => m.tracks).length; const count = result.candidate?.trackCount; links.push({ provider, url: existing.url, status: count != null && count !== expected ? 'CONFLICT' : 'EXISTING', trackCount: count, notes: count != null ? `verified against ${expected} MusicBrainz tracks` : 'MusicBrainz relationship present' }); } else if (result.candidate) { const scored = scoreRelease(release, result.candidate); links.push({ provider, url: result.candidate.url, status: scored.score >= .5 ? 'FOUND' : 'UNVERIFIED', trackCount: result.candidate.trackCount, notes: `${scored.evidence.join('; ')}; score=${scored.score.toFixed(2)}` }); } else { const diag = result.diagnostics.at(-1); links.push({ provider, url: '', status: diag?.status === 'NO_MATCH' ? 'MISSING' : 'UNVERIFIED', notes: diag?.message || 'Provider did not return a candidate' }); } } return { platforms: links, diagnostics }; }
