import type { ProviderCredit, ProviderDiagnostic, ProviderReleaseCandidate, ProviderTrackMetadata, Release } from '../core/models.js';
import { normalizeIsrc, normalizeTrackNumber } from '../core/normalization.js';
import { scoreRelease } from '../core/matching.js';
import { HttpClient } from '../shared/http.js';

export const QOBUZ_CAPABILITIES = { releaseSearch: true, isrc: true, credits: true, platformCheck: true } as const;
const ROLES = new Set(['composer', 'lyricist', 'author', 'writer', 'arranger', 'performance arranger', 'producer', 'co-producer', 'assistant producer', 'mixer', 'mixingengineer', 'mixing engineer', 'engineer', 'assistant engineer', 'recordingengineer', 'recording engineer', 'masteringengineer', 'mastering engineer', 'editor', 'remixer', 'conductor', 'vocals', 'vocal', 'background vocal', 'background vocals', 'musicpublisher', 'music publisher', 'bass', 'drums', 'guitar', 'piano', 'keyboards', 'strings', 'percussion', 'saxophone', 'trumpet']);
function decode(s: string) { return s.replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(Number(n))).replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCodePoint(parseInt(n, 16))).replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&nbsp;/g, ' '); }
export function parseQobuzAlbumUrl(url: string): { id: string; url: string } | undefined { const m = String(url).match(/qobuz\.com\/(?:[a-z]{2}-[a-z]{2}\/)?album\/(?:[^/]+\/)?([a-z0-9]+)/i); return m ? { id: m[1], url: `https://www.qobuz.com/us-en/album/x/${m[1]}` } : undefined; }
export function parseQobuzCreditLine(line: string): Array<{ name: string; roles: string[] }> { const out: Array<{ name: string; roles: string[] }> = []; for (const segment of line.split(' - ')) { const tokens = segment.trim().split(/,\s*/).filter(Boolean); if (!tokens.length || /^\s*(?:copyright|\(p\)|©|℗)/i.test(tokens[0])) continue; const roleAt = tokens.findIndex(t => ROLES.has(t.toLowerCase())); if (roleAt < 0) { out.push({ name: tokens.join(', '), roles: [] }); continue; } const roles = tokens.slice(roleAt); const name = tokens.slice(0, roleAt).join(', '); if (name) out.push({ name, roles }); else if (out.length) out[out.length - 1].roles.push(...roles); } return out; }
export function parseQobuzHtml(html: string, sourceUrl: string): { tracks: ProviderTrackMetadata[]; credits: ProviderCredit[]; candidate: ProviderReleaseCandidate } {
  const tracks: ProviderTrackMetadata[] = []; const credits: ProviderCredit[] = []; const title = decode((html.match(/<meta property="og:title" content="([^"]+)/i)?.[1] || '').replace(/\s*,\s*[^,]+\s*-\s*Qobuz$/i, '')); const artist = decode(html.match(/<meta name="description" content="[^]*? by ([^<]+?) in /i)?.[1] || '');
  const re = /<div class="track__items"[^>]*title="([^"]*)"[\s\S]*?id="popinAddToCartBtnPlayerTrack(\d+)"[\s\S]*?<span class="track__item[^>]*duration">([^<]*)<\/span>[\s\S]*?<p class="track__info">([^<]*)<\/p>/gi; let m: RegExpExecArray | null; while ((m = re.exec(html))) { const num = Number(m[2]); const source = sourceUrl; const duration = m[3].match(/(?:(\d+):)?(\d+):(\d\d)$/); const durationMs = duration ? ((Number(duration[1] || 0) * 60 + Number(duration[2])) * 60 + Number(duration[3])) * 1000 : undefined; tracks.push({ provider: 'qobuz', sourceUrl: source, title: decode(m[1]), artist, trackNumber: num, durationMs, isrcs: [] }); for (const c of parseQobuzCreditLine(decode(m[4]))) for (const role of c.roles) if (!/^main ?artist$|^featured ?artist$|^associated ?performer$/i.test(role)) credits.push({ provider: 'qobuz', sourceUrl: source, trackNumber: num, role: role.toLowerCase(), name: c.name }); }
  const id = parseQobuzAlbumUrl(sourceUrl)?.id || 'unknown'; return { tracks, credits, candidate: { provider: 'qobuz', id, url: sourceUrl, title, artist, trackCount: tracks.length, evidence: ['Qobuz server-rendered track rows'] } };
}
export function parseQobuzApiTracks(payload: any, sourceUrl: string): ProviderTrackMetadata[] { return (payload?.tracks?.items || []).map((t: any, i: number) => ({ provider: 'qobuz', sourceUrl, title: t.title || '', artist: t.performer?.name, trackNumber: t.track_number || i + 1, medium: t.media_number, durationMs: Number(t.duration) * 1000 || undefined, isrcs: [normalizeIsrc(t.isrc)].filter(Boolean) })); }
function qobuzUrl(id: string) { return `https://www.qobuz.com/us-en/album/x/${id}`; }
export async function resolveQobuz(release: Release, http: HttpClient): Promise<{ result?: ReturnType<typeof parseQobuzHtml>; diagnostics: ProviderDiagnostic[] }> {
  const diagnostics: ProviderDiagnostic[] = []; let source = release.links.find(l => l.provider === 'qobuz')?.url; try {
    if (!source) { const q = encodeURIComponent(`${release.artistCredit.map(a => a.name).join(' ')} ${release.title}`); const search = await http.getText(`https://www.qobuz.com/us-en/search?q=${q}`); const urls = [...search.text.matchAll(/href="(https?:\/\/www\.qobuz\.com\/[^"]*\/album\/[^"?]+\/([a-z0-9]+))"/gi)].map(x => x[1]); const candidates = [...new Set(urls)].map(url => ({ provider: 'qobuz', id: parseQobuzAlbumUrl(url)!.id, url, title: decode(url.split('/album/')[1]?.split('/').slice(0, -1).join(' ') || ''), trackCount: undefined } satisfies ProviderReleaseCandidate)); const ranked = candidates.map(c => ({ c, ...scoreRelease(release, c) })).sort((a, b) => b.score - a.score); if (!ranked[0] || ranked[0].score < .28) { diagnostics.push({ provider: 'qobuz', status: 'NO_MATCH', message: 'Qobuz search returned no credible album candidate' }); return { diagnostics }; } source = ranked[0].c.url; }
    const page = await http.getText(source); if (page.status === 401 || page.status === 403) { diagnostics.push({ provider: 'qobuz', status: 'AUTH_REQUIRED', message: `Qobuz page returned ${page.status}`, url: source }); return { diagnostics }; } if (page.status >= 400) { diagnostics.push({ provider: 'qobuz', status: 'NETWORK_ERROR', message: `Qobuz page returned ${page.status}`, url: source }); return { diagnostics }; }
    const result = parseQobuzHtml(page.text, source); if (!result.tracks.length) { diagnostics.push({ provider: 'qobuz', status: 'PARSER_ERROR', message: 'No server-rendered Qobuz track rows found', url: source }); return { diagnostics }; } diagnostics.push({ provider: 'qobuz', status: 'OK', url: source }); return { result, diagnostics };
  } catch (error) { diagnostics.push({ provider: 'qobuz', status: 'NETWORK_ERROR', message: error instanceof Error ? error.message : String(error), url: source }); return { diagnostics }; }
}
export async function qobuzIsrcs(id: string, http: HttpClient): Promise<{ tracks: ProviderTrackMetadata[]; diagnostic: ProviderDiagnostic }> {
  const token = process.env.MBTOOL_QOBUZ_TOKEN; if (!token) return { tracks: [], diagnostic: { provider: 'qobuz', status: 'AUTH_REQUIRED', message: 'Set MBTOOL_QOBUZ_TOKEN to use Qobuz album/get ISRC metadata.' } };
  try { const appId = process.env.MBTOOL_QOBUZ_APP_ID || '712109809'; const data: any = await http.getJson(`https://www.qobuz.com/api.json/0.2/album/get?album_id=${encodeURIComponent(id)}&app_id=${appId}`, { headers: { 'X-App-Id': appId, 'X-User-Auth-Token': token } }); return { tracks: parseQobuzApiTracks(data, qobuzUrl(id)), diagnostic: { provider: 'qobuz', status: 'OK', url: qobuzUrl(id) } }; } catch (error) { return { tracks: [], diagnostic: { provider: 'qobuz', status: 'NETWORK_ERROR', message: error instanceof Error ? error.message : String(error) } }; }
}
