import type { ProviderCredit, ProviderDiagnostic, ProviderReleaseCandidate, ProviderTrackMetadata, Release } from '../core/models.js';
import { normalizeIsrc, normalizeDuration } from '../core/normalization.js';
import { scoreRelease } from '../core/matching.js';
import { HttpClient } from '../shared/http.js';

export const TIDAL_CAPABILITIES = { releaseSearch: true, isrc: true, credits: true, platformCheck: true } as const;
export function parseTidalAlbumUrl(url: string): { id: string; url: string } | undefined { const m = String(url).match(/tidal\.com\/(?:browse\/)?album\/(\d+)/i); return m ? { id: m[1], url: `https://tidal.com/album/${m[1]}` } : undefined; }
function walk(value: any, out: any[] = []): any[] { if (!value || typeof value !== 'object') return out; if (Array.isArray(value)) for (const x of value) walk(x, out); else { if ((value.name || value.title) && (value.role || value.roleName || value.type || value.artist)) out.push(value); for (const x of Object.values(value)) walk(x, out); } return out; }
export function parseTidalCredits(payload: any, sourceUrl: string): { tracks: ProviderTrackMetadata[]; credits: ProviderCredit[] } {
  const tracks: ProviderTrackMetadata[] = []; const credits: ProviderCredit[] = []; const rows = Array.isArray(payload) ? payload : payload?.items || payload?.data || payload?.credits || [];
  const visit = (row: any, fallbackNumber?: number) => { const attrs = row.attributes || row; const num = Number(attrs.trackNumber || attrs.track_number || row.trackNumber || row.track_number || fallbackNumber || 0) || undefined; const title = attrs.title || row.title || ''; if (title && (attrs.isrc || row.isrc || attrs.duration || row.duration)) tracks.push({ provider: 'tidal', sourceUrl, title, trackNumber: num, durationMs: normalizeDuration(attrs.duration || row.duration), isrcs: [normalizeIsrc(attrs.isrc || row.isrc)].filter(Boolean) }); for (const c of [...(row.credits || []), ...(row.contributors || []), ...(row.items || [])]) { const role = c.role || c.roleName || c.type || c.attributes?.role || ''; const person = c.name || c.artist?.name || c.person?.name || c.contributor?.name; if (role && person) credits.push({ provider: 'tidal', sourceUrl, trackNumber: num, role: String(role).toLowerCase(), name: String(person), artistId: c.artist?.id || c.id }); } for (const c of row.credit || []) { if (c.role && (c.name || c.artist?.name)) credits.push({ provider: 'tidal', sourceUrl, trackNumber: num, role: String(c.role).toLowerCase(), name: c.name || c.artist.name, artistId: c.artist?.id }); } };
  rows.forEach((row: any, i: number) => visit(row, i + 1)); for (const row of walk(payload)) { const role = row.role || row.roleName; const person = row.name || row.artist?.name; if (role && person) credits.push({ provider: 'tidal', sourceUrl, role: String(role).toLowerCase(), name: String(person), artistId: row.artist?.id || row.id }); }
  return { tracks, credits };
}
export function parseTidalTracks(payload: any, sourceUrl: string): ProviderTrackMetadata[] { const included = payload?.included || payload?.data || []; return included.filter((x: any) => x.type === 'tracks' || x.attributes?.isrc || x.attributes?.title).map((x: any, i: number) => { const a = x.attributes || x; return { provider: 'tidal', sourceUrl, title: a.title || '', trackNumber: a.trackNumber || a.track_number || i + 1, durationMs: normalizeDuration(a.duration), isrcs: [normalizeIsrc(a.isrc)].filter(Boolean) }; }); }
async function token(http: HttpClient): Promise<string | undefined> { if (process.env.MBTOOL_TIDAL_ACCESS_TOKEN) return process.env.MBTOOL_TIDAL_ACCESS_TOKEN; const id = process.env.MBTOOL_TIDAL_CLIENT_ID; const secret = process.env.MBTOOL_TIDAL_CLIENT_SECRET; if (!id || !secret) return undefined; try { const result: any = await http.postForm('https://auth.tidal.com/v1/oauth2/token', { grant_type: 'client_credentials' }, { headers: { Authorization: `Basic ${Buffer.from(`${id}:${secret}`).toString('base64')}` } }); return result.access_token; } catch { return undefined; } }
export async function resolveTidal(release: Release, http: HttpClient): Promise<{ result?: { tracks: ProviderTrackMetadata[]; credits: ProviderCredit[]; candidate: ProviderReleaseCandidate }; diagnostics: ProviderDiagnostic[] }> {
  const diagnostics: ProviderDiagnostic[] = []; const existing = release.links.find(l => l.provider === 'tidal'); let source = existing?.url; const tok = await token(http); if (!tok) { diagnostics.push({ provider: 'tidal', status: 'AUTH_REQUIRED', message: 'Set MBTOOL_TIDAL_ACCESS_TOKEN or MBTOOL_TIDAL_CLIENT_ID/MBTOOL_TIDAL_CLIENT_SECRET.' }); return { diagnostics }; }
  try {
    const headers = { Authorization: `Bearer ${tok}`, Accept: 'application/vnd.api+json' }; let id = existing && parseTidalAlbumUrl(existing.url)?.id;
    if (!id) { const q = encodeURIComponent(`${release.artistCredit.map(a => a.name).join(' ')} ${release.title}`); const search: any = await http.getJson(`https://openapi.tidal.com/v2/searchResults/${q}?countryCode=US&include=albums`, { headers }); const items: ProviderReleaseCandidate[] = (search.included || search.data || []).filter((x: any) => x.type === 'albums').map((x: any) => ({ provider: 'tidal', id: x.id, url: `https://tidal.com/album/${x.id}`, title: x.attributes?.title || '', artist: x.attributes?.artist?.name, trackCount: x.attributes?.numberOfItems })); const ranked = items.map((c: ProviderReleaseCandidate) => ({ c, ...scoreRelease(release, c) })).sort((a: { score: number }, b: { score: number }) => b.score - a.score); if (!ranked[0] || ranked[0].score < .5) { diagnostics.push({ provider: 'tidal', status: 'NO_MATCH', message: 'Tidal search returned no credible candidate' }); return { diagnostics }; } id = ranked[0].c.id; source = ranked[0].c.url; }
    if (!id) return { diagnostics: [{ provider: 'tidal', status: 'NO_MATCH', message: 'Tidal album could not be resolved.' }] }; source = source || `https://tidal.com/album/${id}`; const payload: any = await http.getJson(`https://tidal.com/v1/albums/${id}/items/credits?replace=true&includeContributors=true&offset=0&limit=100&countryCode=US`, { headers }); const parsed = parseTidalCredits(payload, source); const candidate: ProviderReleaseCandidate = { provider: 'tidal', id, url: source, title: release.title, trackCount: parsed.tracks.length, evidence: ['Tidal credits endpoint'] }; diagnostics.push({ provider: 'tidal', status: 'OK', url: source }); return { result: { ...parsed, candidate }, diagnostics };
  } catch (error) { diagnostics.push({ provider: 'tidal', status: 'NETWORK_ERROR', message: error instanceof Error ? error.message : String(error), url: source }); return { diagnostics }; }
}
export async function tidalIsrcs(id: string, http: HttpClient): Promise<{ tracks: ProviderTrackMetadata[]; diagnostic: ProviderDiagnostic }> { const tok = await token(http); if (!tok) return { tracks: [], diagnostic: { provider: 'tidal', status: 'AUTH_REQUIRED', message: 'Set Tidal credentials to retrieve catalog ISRCs.' } }; try { const url = `https://openapi.tidal.com/v2/albums/${id}/relationships/items?countryCode=US&include=items`; const data: any = await http.getJson(url, { headers: { Authorization: `Bearer ${tok}`, Accept: 'application/vnd.api+json' } }); return { tracks: parseTidalTracks(data, `https://tidal.com/album/${id}`), diagnostic: { provider: 'tidal', status: 'OK', url } }; } catch (error) { return { tracks: [], diagnostic: { provider: 'tidal', status: 'NETWORK_ERROR', message: error instanceof Error ? error.message : String(error) } }; } }
